packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^4.16.2
  '@eslint/markdown': ^6.6.0
  '@slidev/cli': ^52.0.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@types/node': ^24.0.8
  '@types/prompts': ^2.4.9
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-markdown: ^5.1.0
  esno: ^4.8.0
  execa: ^9.6.0
  playwright-chromium: ^1.53.2
  rimraf: ^6.0.1
  vue: ^3.5.17
