name: Prepare Slidev Projects
description: Generate and cache list of slidev projects, detect changes in project list
author: Kent

outputs:
  updated:
    description: Whether the project list has been updated
    value: ${{ steps.check-update.outputs.updated }}

runs:
  using: composite
  steps:
    - name: Restore slidev project list from cache
      id: cache-projects-restore
      uses: actions/cache/restore@v4
      with:
        path: .slidev-projects.list
        key: ${{ runner.os }}-slidev-projects-v1

    - name: Generate slidev project list
      shell: bash
      run: |
        find . -maxdepth 2 -type d -path "./[0-9][0-9][0-9][0-9]-*/src" \
          | cut -d/ -f2 \
          | sort > current.list \
          && cat current.list

    - name: Compare with cached list
      id: check-update
      shell: bash
      run: |
        mkdir -p .github/.cache

        if ! diff -q current.list .slidev-projects.list >/dev/null 2>&1; then
          echo "updated=true" >> $GITHUB_OUTPUT
          cp current.list .slidev-projects.list
        else
          echo "updated=false" >> $GITHUB_OUTPUT
          cat .slidev-projects.list
        fi

    - name: Save slidev project list to cache
      if: steps.check-update.outputs.updated == 'true'
      uses: actions/cache/save@v4
      with:
        path: .slidev-projects.list
        key: ${{ steps.cache-projects-restore.outputs.cache-primary-key }}